### ISSUE TITLE
Remove all the Sass for the `generate-at-breakpoints` mixin as it runs the risk of a large compiled style.css file

### ISSUE THREAD

**Issue by chris-pearce** [westfieldlabs/scally#108]
Discussed on HipChat:

> > Chris Pearce
> > 10:08
> > @here worried about the `generate-at-breakpoints` mixin causing monster CSS files. I'm thinking remove it entirely from Scally, like keep the mixin but that's it then it's up to the fw author to create them when needed maybe in style.scss e.g.
> > Chris Pearce
> > 10:08
> > @import "utilities/u-alignments";
> > @include generate-at-breakpoints('.u-align-v-inline-top',
> >   palm) {
> >   vertical-align: top;
> > }
> > Chris Pearce
> > 10:08
> > @import "utilities/u-alignments";
> > @include generate-at-breakpoints('.u-align-v-inline-top',
> >   palm) {
> >   vertical-align: top;
> > }
> > Chris Pearce
> > 10:08
> > anyway discuss at 11am
> > Chris Pearce
> > 10:13
> > rather than this:
> > Chris Pearce
> > 10:13
> > $u-alignments-breakpoints: palm;
> > @import "utilities/u-alignments";
> > Chris Pearce
> > 10:13
> > which outputs this:
> > Chris Pearce
> > 10:14
> > .u-align-v-inline-top {
> >   vertical-align: top; }
> > @media (max-width: 40em) {
> >   .u-align-v-inline-top-up-to-palm {
> >     vertical-align: top; } }
> > .u-align-v-inline-middle {
> >   vertical-align: middle; }
> > @media (max-width: 40em) {
> >   .u-align-v-inline-middle-up-to-palm {
> >     vertical-align: middle; } }
> > .u-align-v-inline-baseline {
> >   vertical-align: baseline; }
> > @media (max-width: 40em) {
> >   .u-align-v-inline-baseline-up-to-palm {
> >     vertical-align: baseline; } }
> > .u-align-v-inline-bottom {
> >   vertical-align: bottom; }
> > @media (max-width: 40em) {
> >   .u-align-v-inline-bottom-up-to-palm {
> >     vertical-align: bottom; } }
> > .u-align-v-inline-inherit {
> >   vertical-align: inherit; }
> > @media (max-width: 40em) {
> >   .u-align-v-inline-inherit-up-to-palm {
> >     vertical-align: inherit; } }
> > /**
> > - Block level vertical alignments.
> >   _/
> >   .u-align-v-block-middle-flexbox {
> >     display: flex;
> >     align-items: center;
> >     justify-content: center; }
> >   @media (max-width: 40em) {
> >     .u-align-v-block-middle-flexbox-up-to-palm {
> >       display: flex;
> >       align-items: center;
> >       justify-content: center; } }
> >   .u-align-v-block-middle-table {
> >     display: table;
> >     height: 100%;
> >     width: 100%; }
> >   @media (max-width: 40em) {
> >     .u-align-v-block-middle-table-up-to-palm {
> >       display: table;
> >       height: 100%;
> >       width: 100%; } }
> >   .u-align-v-block-middle-table__inner {
> >     display: table-cell;
> >     vertical-align: middle; }
> >   @media (max-width: 40em) {
> >     .u-align-v-block-middle-table__inner-up-to-palm {
> >       display: table-cell;
> >       vertical-align: middle; } }
> >   .u-align-v-block-middle-position {
> >     position: relative;
> >     top: 50%;
> >     transform: translateY(-50%); }
> >   @media (max-width: 40em) {
> >     .u-align-v-block-middle-position-up-to-palm {
> >       position: relative;
> >       top: 50%;
> >       transform: translateY(-50%); } }
> >   /_*
> > - Center align a block level element.
> >   *
> > - 1. Make it work on inline elements e.g. `img`.
> >   */
> >   .u-align-center-block {
> >     display: block;
> >     margin-left: auto;
> >     margin-right: auto; }
> >   @media (max-width: 40em) {
> >     .u-align-center-block-up-to-palm {
> >       display: block;
> >       margin-left: auto;
> >       margin-right: auto; } }
> >   Hide full text
> >   Alec Raeside
> >   10:15
> >   yea it doesnt seem worth it
> >   Chris Pearce
> >   10:15
> >   it's too dangerous
> >   Chris Pearce
> >   10:15
> >   just means its a big non-backwards compatible change to Scally

**Comment by AlecRaeside** [comment]
Can we leave it in for some of them like the display utility?

**Comment by chris-pearce** [comment]
Addressed in #112.
