### ISSUE TITLE
Media query range mixin not allowing for certain ranges

### ISSUE THREAD

**Issue by chris-pearce** [westfieldlabs/scally#125]
Doing this:

```
@include respond-range(lap)
```

You would expect the range to be: **0-1199px** (which is the `lap` range) however it gives you this: **0-900px** (which is `lap-start` to `lap-large-start` range). Same problem with `desk`. 

This is happening because the mixin is just taking the next breakpoint for the `max-width` value.

**Comment by chris-pearce** [comment]
@AlecRaeside could we look at this ASAP before more ppl start using Scally? Cheers.

**Comment by AlecRaeside** [comment]
> however it gives you this: 0-900px

At the moment `@include respond-range(lap)` will produce `@media (min-width: 40.0625em) and (max-width: 56.3125em)`. It uses lap (641px) as the start value and lap-large (901px) as the end value.

**Comment by AlecRaeside** [comment]
I think the functionality you are proposing may be best suited to a new mixin, as this change would make the behaviour of the mixin very different to when the mixin receives 2 numeric values or when the 2nd parameter is a named breakpoint. 

Also, to me matching lap to  0-1199px doesn't make sense as I wouldn't expect a screen width such as 400px wide to be classified in a "lap range". It sounds like what you are proposing is an "up to and including" type of mixin

**Comment by chris-pearce** [comment]
> > Also, to me matching lap to 0-1199px doesn't make sense as I wouldn't expect a screen width such as 400px wide to be classified in a "lap range".

You're totally right and not sure why I said that? Lap range would be: **641px-1199px**.

**Comment by chris-pearce** [comment]
@AlecRaeside any idea when this might get fixed?

**Comment by chris-pearce** [comment]
@AlecRaeside any idea when this might get fixed?

**Comment by AlecRaeside** [comment]
I'm thinking we just remove this mixin all together; lots of mixin complexity with little use. (Alternative is devs write their own media query). What do you think?

**Comment by chris-pearce** [comment]
I dunno I think having the ability to create mq ranges this easily is of value, I know for CC we used a lot of mq ranges.

**Comment by AlecRaeside** [comment]
@chris-pearce To confirm expectations for this mixin should `@include respond-range(lap-large) {}` generate a media query for 901px to 1199px?

What should it generate when used like this? `@include respond-range(palm) {}`

Also, I propose we rename this mixin to `respond-to-range`

**Comment by chris-pearce** [comment]
> > should @include respond-range(lap-large) {} generate a media query for 901px to 1199px?

Correct.

> > What should it generate when used like this? @include respond-range(palm) {}

We don't need that as even though it is technically a range: **0-640px** we'd just use a max width mq so:

```
@include respond-to(palm, max)
```

So it'll only be these 3 for the set bp's: https://github.com/westfieldlabs/scally/blob/master/core/settings/_breakpoints.scss#L53-L57 and should except any 2 custom bp's as shown here: https://github.com/westfieldlabs/scally/blob/master/core/mixins/_media-queries.scss#L30-L32.

**Comment by AlecRaeside** [comment]
what will the 'max' value be when desk is specified? desk-large?

**Comment by chris-pearce** [comment]
> > what will the 'max' value be when desk is specified? desk-large?

No `desk`.

**Comment by AlecRaeside** [comment]
sorry, I was supposed to what will the 'max' value be when desk is specified as the 'min' value?

**Comment by chris-pearce** [comment]
Not sure I follow? If you did this:

```
@include respond-to(desk)
```

Which is a `min` value it would render at `1200px +`.

**Comment by AlecRaeside** [comment]
I mean if it was passed into the respond-range mixin. eg `@include respond-range(desk)`

**Comment by AlecRaeside** [comment]
it could throw an error or just use desk-large as the max

**Comment by chris-pearce** [comment]
I'd go with `desk-large` as the max.
