### ISSUE TITLE
Utilities and breakpoints

### ISSUE THREAD

**Issue by AlecRaeside** [westfieldlabs/scally#4]
In the todo: "Every Utility needs to be applied via all the main breakpoints"

I think this ability should only be available to some utilities. This will limit the flexibility of scally but will reduce the filesize:

Arrows: no
Blocklist: no
Bottom Spacing: no
Box: yes
Clearfix: no
Columns: yes
Complex Link: no
Disguised Link: no
Display: yes
Divider: yes
Drop Down: yes
Flag: yes
Float: yes
Hardware Accelerated: yes
Hide: yes
Horizontal List: yes
Image Replacement: no
New Block Formatting Context: no
Overlay: yes
Preserve aspect ratio: no
Pull: yes
Skip Link: no
Slats: yes
Smooth Touch Scrolling: yes
spacing: YES
split: yes?
Sprite bg: no
Sprite icon: no
Text: yes
Toggle Visibility: yes
Transitions: no
Vertical alignment: yes
Widths: yes

**Comment by chris-pearce** [comment]
I agree and for some we only need to apply `palm` and `non-palm` not **ALL** (ALL bp's is a special case really). BTW the above list will be getting redone with Scally.

**Comment by chris-pearce** [comment]
BTW `non-palm` doesn't exist anymore, it's just `lap` now.
