### ISSUE TITLE
Update generate-at-breakpoints to support max width mq

### ISSUE THREAD

**Issue by kllevin** [westfieldlabs/scally#74]
The generate-at-breakpoints mixin doesn't allow max width mq on arbitrary no's only the named bp: palm.

**Comment by chris-pearce** [comment]
@AlecRaeside don't forget to reference issues when you merge PR's, the standard is to say in the PR:

> > This closes #Issue no

And to close the Issue.

Cheers

**Comment by AlecRaeside** [comment]
ah, forgot about this feature, very cool. updated the pr
