### ISSUE TITLE
Expose scss-lint config via bower

### ISSUE THREAD

**Issue by AlecRaeside** [westfieldlabs/scally#91]
The .scss-lint.yml config file should be included in the files that are published via bower. This will allow projects that use scally to share the same linting config.

**Comment by chris-pearce** [comment]
@AlecRaeside how we going with this? Seems like it would be a really quick job?

**Comment by AlecRaeside** [comment]
This will be done as part of this story https://jira.westfieldlabs.com/browse/GPP-831 which was originally going to be done as part of this sprint but got pushed out due to focus on navigation

**Comment by chris-pearce** [comment]
OK.

**Comment by chris-pearce** [comment]
@AlecRaeside I'll take this on.
