### ISSUE TITLE
Target headings mixin not working

### ISSUE THREAD

**Issue by chris-pearce** [westfieldlabs/scally#94]
@AlecRaeside determined that this mixin doesn't work properly at all.

**Comment by chris-pearce** [comment]
@AlecRaeside could you take a look when you can?

**Comment by AlecRaeside** [comment]
yep

**Comment by chris-pearce** [comment]
@AlecRaeside any joy with this?

**Comment by chris-pearce** [comment]
@AlecRaeside if you could look at this especially now it's not working, otherwise I'll just remove it from Scally entirely. Cheers.
